### ISSUE TITLE
Don't refer to elementary OS in your appdata file

### ISSUE THREAD

**Issue by danirabbit** [BharatKalluri/Gifup#13]
https://github.com/BharatKalluri/Gifup/blob/1936b096c48a199453041acfccfce5f4d45c6fe0/data/com.github.bharatkalluri.gifup.appdata.xml#L10

everything published through AppCenter dashboard is made for elementary OS, so this is redundant information.

**Comment by BharatKalluri** [comment]
removed reference to elementary os.
