### ISSUE TITLE
About action broken

### ISSUE THREAD

**Issue by danirabbit** [BharatKalluri/Gifup#16]
https://github.com/BharatKalluri/Gifup/blob/d23bc57ffc4e60ecde60d1cd80758f48ff9776b7/data/com.github.bharatkalluri.gifup.desktop#L16

since https://github.com/BharatKalluri/Gifup/commit/623ed4bcf4fea2659a0903c6891110c25b8ec106 the binary has been renamed

**Comment by BharatKalluri** [comment]
Hey @danrabbit 

Should I do a release or will a commit be fine?

never mind, did a new release.

**Comment by BharatKalluri** [comment]
Fixed :+1:
