### ISSUE TITLE
An error occurred, Please try again.

### ISSUE THREAD

**Issue by robertsanseries** [BharatKalluri/Gifup#21]
Follow these steps:

1 - Open the application
2 - Do not select any files
3 - click on MAKE GIF

![captura de tela de 2017-09-16 23-26-40](https://user-images.githubusercontent.com/11967501/30517464-918d9d1a-9b36-11e7-93b3-e1e8ed9b3183.png)

Nota: I believe the button should only be enabled after selecting a file

**Comment by BharatKalluri** [comment]
Changed in Release 0.0.9.
