### ISSUE TITLE
Is getting the time in seconds the best option?

### ISSUE THREAD

**Issue by robertsanseries** [BharatKalluri/Gifup#23]
It is easier for a user to know the common video time.

- Ex: (00:01:54: 31.00)

You can use GLib.Regex to configure and validate the input block and then convert it to seconds in the backend. Check the "duration_in_seconds" method of my TimeUtil class to get the value in seconds.

https://github.com/robertsanseries/ciano/blob/master/src/utils/TimeUtil.vala

**Comment by BharatKalluri** [comment]
Changed in Release 0.0.9.
