### ISSUE TITLE
Icon and banner color too similar 

### ISSUE THREAD

**Issue by Philip-Scott** [BharatKalluri/Gifup#25]
The banner color you picked is too similar, (or the same) as the icon, and makes it hard to see

![screenshot from 2017-09-17 11 51 20](https://user-images.githubusercontent.com/10786508/30522994-918533f6-9b9e-11e7-9a47-31036d424fca.png)

**Comment by BharatKalluri** [comment]
The color of the banner was changed after it was mentioned in #18 , Now the Appcenter looks like this
![gifup](https://user-images.githubusercontent.com/8049414/30525464-7f06c1aa-9c24-11e7-9aa6-0ba6d113a13a.png)
