### ISSUE TITLE
graphic interaction

### ISSUE THREAD

**Issue by robertsanseries** [BharatKalluri/Gifup#26]
It would be interesting to see the possibility of defining the cut graphically.

![68747470733a2f2f7468756d62732e6766796361742e636f6d2f486967684163636c61696d6564416e61636f6e64612d73697a655f726573747269637465642e676966](https://user-images.githubusercontent.com/11967501/30773625-8c4908f8-a04a-11e7-86c4-9784d51ebc0f.gif)

**Comment by BharatKalluri** [comment]
I am not sure If I can code such a complicated widget from ground up :)

But I thought having a second by second control would be useful. So I introduced a time picker. Maybe I'll consider making this in the future.
