### ISSUE TITLE
Invalid URL for screenshot

### ISSUE THREAD

**Issue by danirabbit** [BharatKalluri/Gifup#27]
https://github.com/BharatKalluri/Gifup/blob/7e3b4dcd65ab99b016fa40298d21b9f83cfda8ab/data/com.github.bharatkalluri.gifup.appdata.xml#L28

This should be `https://raw.githubusercontent.com/BharatKalluri/Gifup/master/Screenshot.png`

**Comment by BharatKalluri** [comment]
Thanks! Fix done!
