### ISSUE TITLE
End time  - not working

### ISSUE THREAD

**Issue by peakgeek** [BharatKalluri/Gifup#34]
Hello,

Awesome app BTW, thank you. I just updated to the latest version and setting an end-time doesn't appear to be working. The gif output begins at the desired start time, but then continues on to the end of the video (ignoring the end time set). Just wanted to point this out, and if there is something I might be missing, please let me know.

Thanks!!!

**Comment by BharatKalluri** [comment]
Hey @peakgeek ,

Just released 0.0.14. This should fix the issue. Let me know if it still persists.

Cheers!

**Comment by peakgeek** [comment]
Working great! Thank you so much. Do you have plans of submitting this to elementary's AppCenter?

**Comment by BharatKalluri** [comment]
@peakgeek , weird... I submitted to the app center and it tells me that the application is deployed in the app center. I can not find it on my machine's app center.
Can you see gifup in your app center?

**Comment by peakgeek** [comment]
No, I don't see it either, but I'm pretty sure that's were I found it originally. After your quick response and fix to the app, I went looking for it in the AppCenter hoping to contribute just out of appreciation, but couldn't find it. Keep me posted.

**Comment by BharatKalluri** [comment]
The app is up and running in app center @peakgeek ! Download and give it a try!

**Comment by BharatKalluri** [comment]
Closing this issue as it is fixed and the update is live on app store. Feel free to open it again if you face any problems @peakgeek.
