### ISSUE TITLE
could you make a flatpak for Gifup?

### ISSUE THREAD

**Issue by ghost** [BharatKalluri/Gifup#36]
Hi, I really appreciate your work , is a good application
but i don't use elementary OS
could you make a flatpak for Gifup?
in this way, users can install the application in any linux distribution

please.
thank you.

**Comment by BharatKalluri** [comment]
Hello @altntowin !
Thanks for the compliment! I really want to package the application as a flatpak but don't have the time to do so. If anyone is willing to, I would be happy to help :-)

**Comment by BharatKalluri** [comment]
Flatpak support has been added! Will upload it to flathub when I find time.
