### ISSUE TITLE
Resize options

### ISSUE THREAD

**Issue by arjunmenon** [BharatKalluri/Gifup#39]
Hey
At present the app allows to set only the width.
It would be also good if there was an option to edit the height with it.

Why?

Because, I am using this app to upload work to Dribbble and they only accept gifs with a set dimensions like 400x300 or 800x600

To keep the aspect ratio, perhaps a draggable crop option can be introduced, so layout inside the defined box, is the layout which gets rendered as Gif.

**Comment by BharatKalluri** [comment]
Added initial support for height in the new release.
