### ISSUE TITLE
Logo that is suitable for elementary os

### ISSUE THREAD

**Issue by brigazvi** [BharatKalluri/Gifup#40]
This is my experience in this matter:
![gifup](https://user-images.githubusercontent.com/37640970/41819633-5b2319d0-77cc-11e8-8e43-fa35a82087c5.png)

this is 128x128 version.
Do you want me to make versions of all sizes?

**Comment by brigazvi** [comment]
in good resolution:
![gifup](https://user-images.githubusercontent.com/37640970/41819652-ac59de38-77cc-11e8-909a-be907cdb4f19.png)

**Comment by BharatKalluri** [comment]
I do have svg's of all icon sizes over at https://github.com/BharatKalluri/Gifup/tree/master/data/icons.

Do you want to add more sizes?

**Comment by brigazvi** [comment]
@BharatKalluri 
i created a pull request:
https://github.com/BharatKalluri/Gifup/pull/41
It has a travis ci error.
I do not know why.

**Comment by BharatKalluri** [comment]
Thanks!
