### ISSUE TITLE
Screenshot doesn't show elementary OS defaults

### ISSUE THREAD

**Issue by danirabbit** [BharatKalluri/Gifup#50]
I've marked the latest update of Gifup as "Needs fixing" due to the screenshot. Screenshots in AppCenter must use elementary OS default settings.

Please also use the default screenshot tool to get a screenshot with a transparent background. You can do this by selecting "Grab the current window"

**Comment by BharatKalluri** [comment]
Added elementary Screenshot using the defaults.
